### ISSUE TITLE
Username must not be null! issue

### ISSUE THREAD

**Issue by syed-growexxer** [EjaraApp/trustdart#37]
I have attached environment variables in local properties,
still it says 
Username must not be null!

**Comment by jayluxferro** [comment]
Hi @syed-growexxer , you need to create an environment variable on your machine and set the following:

TRUST_DART_GITHUB_USER=""
TRUST_DART_GITHUB_TOKEN=""

On Linux you can add it to your `~/.bashrc`, on macOS if you're using `zsh` then use `~/.zshrc`. On windows please use the system environment variables.

* You first need to setup a personal access token for github as decribed here, https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token .
* You only need to select `read:package` scope.
